import struct
import numpy as np

import tkinter as tk
from PIL import Image, ImageTk

SPECTRUM_MAGIC = 0x4D435259
MIN_DB, MAX_DB = -50.0, 30.0
MAX_FREQ = 3100

VARA_STOPS = [
    [0.00, 0, 0, 0],
    [0.10, 0, 0, 40],
    [0.20, 0, 0, 120],
    [0.30, 0, 30, 180],
    [0.40, 0, 100, 200],
    [0.50, 0, 180, 130],
    [0.60, 40, 220, 40],
    [0.70, 200, 220, 0],
    [0.80, 255, 160, 0],
    [0.90, 255, 60, 0],
    [1.00, 255, 255, 255],
]  # VARA Colormap (from waterfall_widget.py _build_vara_colormap)


# generated by mimo-v2.5
def parse_spectrum(data):
    """解析 Mercury 频谱二进制帧，返回 (fft_size, sample_rate, dB_array) 或 None"""
    if len(data) < 8:
        return None
    magic, fft_size, sample_rate = struct.unpack_from("<IHH", data, 0)
    if magic != SPECTRUM_MAGIC:
        return None
    expected = 8 + fft_size * 4
    if len(data) < expected:
        return None
    dB = np.frombuffer(data[8:expected], dtype="<f4").copy()
    return fft_size, sample_rate, dB


def db2color(db):
    t = (db - MIN_DB) / (MAX_DB - MIN_DB)
    return max(0, min(255, round(t * 255)))


class Waterfall:
    def __init__(self, canvas: tk.Canvas):
        self.canvas = canvas
        self.image = None
        self.photo = None
        self._img_id = None
        self.build_lut()
        canvas.bind("<Configure>", self.on_resize)

    def build_lut(self):
        self.colorLUT = []
        for i in range(256):
            t = i / 255
            for j in range(len(VARA_STOPS)):
                if t >= VARA_STOPS[j][0] and t <= VARA_STOPS[j + 1][0]:
                    lo = VARA_STOPS[j]
                    hi = VARA_STOPS[j + 1]
                    f = 0 if hi[0] == lo[0] else (t - lo[0]) / (hi[0] - lo[0])
                    self.colorLUT.append(
                        (
                            round(lo[1] + f * (hi[1] - lo[1])),
                            round(lo[2] + f * (hi[2] - lo[2])),
                            round(lo[3] + f * (hi[3] - lo[3])),
                        )
                    )
                    break

    # generated by mimo-v2.5
    def on_resize(self, event):
        """Canvas 缩放时重建 Image 并重绘"""
        new_w, new_h = event.width, event.height
        if new_w < 1 or new_h < 1:
            return
        if self.image is None or self.image.size != (new_w, new_h):
            old_img = self.image
            self.image = Image.new("RGB", (new_w, new_h), (0, 0, 0))
            # 用黑色填充新区域
            if old_img is not None:
                # 尝试把旧内容缩放粘贴到新尺寸
                resized = old_img.resize((new_w, new_h), Image.Resampling.NEAREST)
                self.image.paste(resized, (0, 0))
            self.refresh_photo()

    # generated by mimo-v2.5
    def refresh_photo(self):
        self.photo = ImageTk.PhotoImage(self.image)
        if self._img_id is None:
            self._img_id = self.canvas.create_image(0, 0, anchor="nw", image=self.photo)
        else:
            self.canvas.itemconfig(self._img_id, image=self.photo)

    # generated by mimo-v2.5
    def push(self, fft_size: int, sample_rate: int, dB: np.ndarray):
        """推送一行频谱数据, 滚动并绘制"""
        if self.image is None:
            return
        w, h = self.image.size
        scroll = 5
        display_bins = int(MAX_FREQ / (sample_rate / 2) * fft_size)
        # 向下滚动
        if h > scroll:
            region = self.image.crop((0, 0, w, h - scroll))
            self.image.paste(region, (0, scroll))
        # 生成新行像素
        pixels = self.image.load()
        if pixels:
            for x in range(w):
                bin_idx = int(x / w * display_bins)
                if bin_idx >= len(dB):
                    break
                r, g, b = self.colorLUT[db2color(dB[bin_idx])]
                for row in range(scroll):
                    pixels[x, row] = (r, g, b)
        self.refresh_photo()
