name: Release

on:
  release:
    types:
      - published

jobs:

  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v5
      - name: Setup Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build
        run: pyinstaller -F -w -n mercury-tk src/app.py
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: auto-pack-windows
          path: dist/mercury-tk.exe

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v8
        with:
          name: auto-pack-windows
          path: dist/
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/mercury-tk.exe
